services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3100:3000"
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - ./var/lib/heimdall:/config
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Canberra
    restart: always

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./var/lib/homeassistant:/config
    ports:
      - "8123:8123"
    environment:
      - TZ=Australia/Canberra
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    volumes:
      - ./var/lib/pihole/etc-pihole:/etc/pihole
      - ./var/lib/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "8444:443/tcp"
      - "67:67/udp"
    environment:
      - TZ=Australia/Canberra
      - WEBPASSWORD=admin123
    cap_add:
      - NET_ADMIN
      - SYS_NICE

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=gethomepage.dev
      - PUID=1000
      - PGID=1000
    ports:
      - "3000:3000"
    volumes:
      - ./var/lib/homepage:/app/config
    restart: unless-stopped



















