version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3100:3000"
    volumes:
      - ./var/lib/grafana

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - ./var/lib/heimdall
    ports:
      - "443:443"
    restart: always

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./var/lib/homeassistant
    ports:
      - "8123:8123"
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    volumes:
      - ./var/lib/pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "8443:443/tcp"
      - "67:67/udp"
    cap_add:
      - NET_ADMIN
      - SYS_NICE

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev
      PUID: 1000
      PGID: 1000
    ports:
      - "3000:3000"
    volumes:
      - ./app/config
    restart: unless-stopped



















